-- AlterTable
ALTER TABLE `Proposal` MODIFY `submittedStatus` ENUM('PROPOSED', 'REJECTED_CLIENT', 'REJECTED_INTERNAL', 'IN_PROCESS', 'SELECTED', 'SUBMITTED', 'JOINED', 'DROPPED', 'DROPPED_CLIENT', 'DROPPED_INTERNAL') NULL;
