-- AlterTable
ALTER TABLE `Token` ADD COLUMN `parentTokenId` VARCHAR(36) NULL,
ADD COLUMN `isRevoked` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
ADD COLUMN `revokedAt` TIMESTAMP(6) NULL;


