-- CreateTable
CREATE TABLE `FutureJobsProfile` (
    `id` VARCHAR(36) NOT NULL,
    `profileId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `contact` VARCHAR(191) NOT NULL,
    `jobSkill` VARCHAR(191) NULL,
    `jobRole` VARCHAR(191) NULL,
    `location` VARCHAR(191) NOT NULL,
    `readyToRelocate` VARCHAR(191) NULL,
    `nationality` VARCHAR(191) NOT NULL,
    `nativeLanguage` VARCHAR(191) NOT NULL,
    `jobLanguage` VARCHAR(191) NOT NULL,
    `languageLevel` VARCHAR(191) NOT NULL,
    `noticePeriod` VARCHAR(191) NOT NULL,
    `salary` VARCHAR(191) NOT NULL,
    `salaryCurrency` VARCHAR(191) NOT NULL,
    `profileForClient` VARCHAR(191) NOT NULL,
    `profileForJobRole` VARCHAR(191) NOT NULL,
    `currentCompany` VARCHAR(191) NULL,
    `education` VARCHAR(191) NULL,
    `totalYearOfExp` VARCHAR(191) NULL,
    `profileSource` VARCHAR(191) NULL,
    `profileSourceLink` VARCHAR(191) NULL,
    `availability` VARCHAR(191) NULL,
    `availabilityDate` DATETIME(3) NULL,
    `recruiterNotes` VARCHAR(191) NULL,
    `resume` VARCHAR(191) NULL,
    `submissionDate` DATETIME(3) NULL,
    `submittedBy` VARCHAR(191) NULL,
    `lastUpdate` DATETIME(3) NULL,
    `createdById` VARCHAR(191) NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` DATETIME(3) NULL,
    `status` VARCHAR(191) NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
