-- AlterTable
ALTER TABLE `Proposal` MODIFY `submittedStatus` ENUM('PROPOSED', 'REJECTED_CLIENT', 'REJECTED_INTERNAL', 'IN_PROCESS', 'ROLE_HOLD', 'ROLE_CLOSED', 'SELECTED', 'SUBMITTED', 'JOINED', 'DROPPED_CLIENT', 'DROPPED_INTERNAL', 'PENDING_SUBMISSION') NULL;
